### ISSUE TITLE
Wired zooming in effect on low hunger

### ISSUE THREAD

**Issue by Aiena-RPG** [squeek502/AppleCore#118]
With Applecore installed on our server, we are experiencing a wired flickering change in the fov when the player has a low hunger value (as if one were using the sprint key really fast). This occurs only when we use AppleCore even without any other mods interacting with AppleCore installed. Nevertheless here is the Modlist of our Pack:
antiqueatlas
AppleCore
AppleSkin
BackTools
BetterWithMods
blockdrops
Ceramics
Chisel
CraftStudio
CTM
CoustomNPCs
Decocraft
ediblebugs
faction
ForgeCraft
Hwyla
iChunUtil
jei
JustEnoughResources
Level+Up!
Mantle
Pam's+HarvestCraft
preview_OptiFine
PrimalCore
RealisticItemDrops
rustic
signpost
Tech+Ores
ToughAsNails
worldedit
WorldProtector

We are using Version 3.1.1 but the bug also occurs on the previous version. We are using Minecraft 1.12.2 and forge 1.12.2-14.23.1.2583

**Comment by squeek502** [comment]
Just to be sure, does it still happen when AppleCore is not installed?

**Comment by Aiena-RPG** [comment]
It does not happening when AppleCore is not installed. We tested this to make sure we we file a bug report to the right person.

**Comment by squeek502** [comment]
Is it possible for you to test if it still happens when AppleCore is the only mod you have installed?

I'm not really sure how AppleCore could be doing this, as [AppleCore does very little on its own](https://github.com/squeek502/AppleCore/wiki/AppleCore-features), and there is nothing in the AppleCore code that checks for low hunger in any way. My only guess is that there is some very strange cross-mod bug going on or something.

**Comment by Aiena-RPG** [comment]
We will check this, and will find out which mod causes this wired issue. We contact you as soon, as we find out.

**Comment by Aiena-RPG** [comment]
Took us long, but we found the issue, it was indeed not your mod, therefore this pull request can be closed.
