### ISSUE TITLE
Server side bug: petals of botania now do not grow.

### ISSUE THREAD

**Issue by foxbeta90** [squeek502/AppleCore#63]
I have updated the version of Applecore from 3.0 to 3.1 to fix the buf of the crash using the bonemeal on the botania's petals.
Now the petals do not grow on server ( only on single player mode ).
Just reporting this in case this is a bug related to the changes of this version.

**Comment by squeek502** [comment]
Yeah, it's definitely related. The 'fix' I put in 1.3.1 is really bad--instead of crashing it will just stop the fertilize method from being called entirely. I'm probably just going to remove the entire fertilization part of the AppleCore API, as it's just been a headache with no benefits (no mod is actually using any part of it afaik).

Appreciate the report.

**Comment by squeek502** [comment]
Found a potential fix, committed here: f62ad21575bb1c53908d389a07c7a58e735425d1

Will close this once I'm able to test it a bit more and confirm that the fix doesn't have any side-effects.

**Comment by ghost** [comment]
Thanks for the quick reply :D

**Comment by squeek502** [comment]
@foxbeta90 which Minecraft version are you running? I'd like to give you a test version to try out and see if it works for you.

**Comment by squeek502** [comment]
Fixed in 1.3.2
