### ISSUE TITLE
Example for new API in Wiki

### ISSUE THREAD

**Issue by mainrs** [squeek502/AppleCore#87]
Looks like you deprecated the old API methods from `dispatcher`. Would love to see some examples for the replacement. I am quite new to modding and don't really have a clue on how to use them.

**Comment by squeek502** [comment]
The replacement is the Forge events that do roughly the same thing. Specifically, AppleCore's `AllowGrowthTick` is replaced by `CropGrowEvent.Pre`, and AppleCore's `GrowthTick` is replaced by `CropGrowEvent.Post`.

- [The relevant source code](https://github.com/MinecraftForge/MinecraftForge/blob/c545b8ecd4e96107ccf134c8fd89906357d586ad/src/main/java/net/minecraftforge/event/world/BlockEvent.java#L301-L355)
- [The relevant pull request](https://github.com/MinecraftForge/MinecraftForge/pull/3320)
- [Example usage (linked from the PR)](https://github.com/Draco18s/ReasonableRealism/blob/Farming-Example/src/main/java/com/draco18s/farming/FarmingEventHandler.java)

For the `dispatcher` specifically, you can look at [the implementation of the deprecated methods to see how they fire the Forge events](https://github.com/squeek502/AppleCore/blob/1.10.2/java/squeek/applecore/api_impl/AppleCoreDispatcherImpl.java#L27-L49) (note: it would probably make more sense for you to use Forge's `ForgeHooks.onCropsGrowPre` and `ForgeHooks.onCropsGrowPost` methods instead of firing the events manually).

Hope that helps.
